/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdTypes.h"
#include "errorStates.h"
#include "stm32f103.h"

#include "RCC_int.h"
#include "GPIO_Int.h"

int const x = 4;
int main(void)
{
	
	
    /* Loop forever */
	PinConfig_t Port = {
			.Port=PORTB,
			.PinNum=PIN4,
			.PinDirection=OUTPUT,
			.INConfig = IN_PULLUP_PULLDOWN,
			.OUTConfig = PUSH_PULL,
	};
	RCC_enuAPB2_EnableClock(IOPB);

	//GPIO_enuInit(&Port);
	__asm volatile ("msr msp,r3");
	//GPIO_enuSetPinValue(PORTB,PIN4,PIN_LOW);

	for(;;)
	{
	//	GPIO_enuSetPinValue(PORTA,PIN1,PIN_HIGH);
	}
	

}
void MemManage_Handler(void)
{
}